name: pr
on:
  push:
    branches:
      - "pull-request/[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  pr-builder:
    needs:
      - checks
      - cpp-build-test
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@cuda-13.3.0
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  checks:
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@cuda-13.3.0
    with:
      enable_check_generated_files: false
      enable_check_version_files_changed: false
      enable_check_version_against_tag: false
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
  cpp-build-test:
    needs: checks
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@cuda-13.3.0
    with:
      build_type: pull-request
      script: ci/build_and_test.sh
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: read
      pull-requests: read
